name: price_scout_nz
description: A Flutter app for comparing prices across NZ retailers.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.4
  firebase_core: ^2.7.0
  location: ^5.0.3
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/